-- NeuroMax Personal — Supabase schema.
-- Run in the Supabase SQL editor (or psql). RLS is enabled with permissive
-- single-user policies suitable for personal use; tighten for multi-user.

create table if not exists users (
  id          bigint generated by default as identity primary key,
  email       text unique not null,
  password_hash text not null,
  settings    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create table if not exists portfolios (
  id         bigint generated by default as identity primary key,
  user_id    text not null,
  balance    numeric not null default 0,
  holdings   jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists signals (
  id         bigint generated by default as identity primary key,
  user_id    text not null,
  symbol     text not null,
  action     text not null check (action in ('BUY','SELL','HOLD','WATCH')),
  confidence int,
  risk_score int,
  auto       boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_signals_user on signals(user_id, created_at desc);

create table if not exists trades (
  id         bigint generated by default as identity primary key,
  user_id    text not null,
  symbol     text not null,
  action     text not null,
  price      numeric not null,
  amount     numeric not null,
  executed   boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_trades_user on trades(user_id, created_at desc);

create table if not exists alerts (
  id         bigint generated by default as identity primary key,
  user_id    text not null,
  name       text not null,
  rule       jsonb not null,
  symbol     text,
  status     text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists backtest_results (
  id         bigint generated by default as identity primary key,
  user_id    text not null,
  symbol     text not null,
  strategy   text not null,
  params     jsonb not null default '{}'::jsonb,
  stats      jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Realtime: broadcast new signals/alerts to subscribed clients.
alter publication supabase_realtime add table signals;
alter publication supabase_realtime add table alerts;
